FROM openjdk:21-jdk-slim

# Set working directory
WORKDIR /app

# Copy the built JAR file (adjust the path and name)
COPY build/libs/demo_test.jar demo_test.jar

# Set command to run the JAR
ENTRYPOINT ["java", "-jar", "demo_test.jar"]